#!/bin/bash

if [[ $EUID -eq 0 ]]; then
    echo "Don't run as root."
    exit 1
fi

(cd /opt/lanmomo/ && NODE_ENV=prod forever start -a -l /var/log/lanmomo/forver.log -o /var/log/lanmomo/stdout.log -e /var/log/lanmomo/stderr.log app.js)
